* Introduction 

#+BEGIN_SRC R :post round-tbl[:colnames yes](*this*)
A <- matrix(1, nrow = 400, ncol = 300)
B <- matrix(1, nrow = 300, ncol = 30)
C <- matrix(1, nrow = 30, ncol = 500)
D <- matrix(1, nrow = 500, ncol = 400)

library(microbenchmark)

res <- microbenchmark(A %*% B %*% C %*% D, ((A %*% B) %*% C) %*% D, (A %*% (B %*% C)) %*% D, (A %*% B) %*% (C %*% D), A %*% (B %*% (C %*% D)), A %*% ((B %*% C) %*% D))

options(microbenchmark.unit = "relative")
print(res, signif = 3, order = "mean")
#+END_SRC

The approach we take in chapter 2 is to delay the evaluation of matrix multiplication and instead build a data structure for matrix expressions, one we can evaluate later when we have the entire matrix multiplication expression constructed. It is a simple domain specific language, but it contains all the components we typically need in one: we need code for parsing an expression and creating a representation of it, we need to do some manipulation of expressions, and we need to evaluate them. 

For parsing expressions, we need to capture matrixes and multiplications. We wrap matrices in a class to make them objects of our language, rather than plain R data: 

#+BEGIN_SRC R :post round-tbl[:colnames yes](*this*)
# overload multiplication operator
m <- function(data) {
    structure(data,
              nrow = nrow(data),
              ncol = ncol(data),
              class = c("matrix_expr", class(data)))
}

# save references to matrices we want to multiply together
matrix_mult <- function(A, B) {
    structure(list(left = A, right = B),
              nrow = nrow(A),
              ncol = ncol(B),
              class = c("matrix_mult", "matrix_expr"))
}

`*.matrix_expr` <- function(A, B) {
    matrix_mult(A, B)
}

# syntactic sugar for A %*% B %*% C %*% D
# this constructs a data structure representation, but doesn't eval
m(A) * m(B) * m(C) * m(D)
list(A, B, C, D) %>% reduce(., ~ m(.x))

# eval mmult
v <- function(expr) eval_matrix_expr(rearrange_matrix_expr(expr))
#+END_SRC

* Matrix Expressions 

Our goal for writing a language for matrix expressions is to improve upon the default performance of the built-in matrix expressions. We achieve this by taking a more global view of expressions than R does. R handles each operator one at a time from left to right, but we will analyze expressions and rearrange them to improve performance. These are the steps we must take to do this: 

1. parse expressions into data that we can manipulate
2. rearrange the expressions into more efficient expressions
3. provide a way to evaluate the expressions 

** Parsing Expressions 

To keep things simple, we only consider matrix multiplication and matrix addition. We do not include scalar multiplication or inverting or transposing matrices. 

With these restrictions, we can say that a matrix expression is either just a matrix, the product of two matrix expressions, or the sum of two matrix expressions. We represent this as a class hierarchy with one abstract superclass for expressions, and three concrete classes representing data, products, and sums. 

#+BEGIN_SRC R :post round-tbl[:colnames yes](*this*)
# constructors
m <- function(data) {
    structure(list(data = data),
              nrow = nrow(data),
              ncol = ncol(data),
              # for pretty printing
              def_expr = deparse(substitute(data)),
              class = c("matrix_data", "matrix_expr"))
}

matrix_mult <- function(A, B) {
    structure(list(left = A,
                   right = B),
              nrow = nrow(A),
              ncol = ncol(B),
              class = c("matrix_mult", "matrix_expr"))
}

matrix_sum <- function(A, B) {
    structure(list(left = A,
                   right = B),
              nrow = nrow(A),
              ncol = ncol(B),
              class = c("matrix_sum", "matrix_expr"))
}

# helper functions for matrix expressions for pretty printing
toString.matrix_data <- function(x, ...) {
    paste0("[", attr(x, "def_expr"), "]")
}

toString.matrix_mult <- function(x, ...) {
    paste0("(", toString(x$left), " * ", toString(x$right), ")")
}

toString.matrix_sum <- function(x, ...) {
    paste0("(", toString(x$left), " + ", toString(x$right), ")")
}

print.matrix_expr <- function(x, ...) {
    cat(toString(x), "\n")
}

# try constructing a small expression
A <- matrix(1, nrow = 10, ncol = 20)
B <- matrix(1, nrow = 20, ncol = 10)
C <- matrix(1, nrow = 10, ncol = 10)

matrix_sum(matrix_mult(m(A), m(B)), m(C))

# overload the multiplication and addition operators for mat_exprs
`*.matrix_expr` <- function(A, B) {
    stopifnot(ncol(A) == nrow(B))
    matrix_mult(A, B)
}

`+.matrix_expr` <- function(A, B) {
    stopifnot(dim(A) == dim(B))
    matrix_sum(A, B)
}

m(A) * m(B) + m(C)

# use dim function for the addition operator 
dim.matrix_expr <- function(x) {
    c(attr(x, "nrow"),
      attr(x, "ncol"))
}
#+END_SRC

** Meta-Programming Parsing 

Given an expression that doesn't use the m function, we can transform it into one that does like this 

#+BEGIN_SRC R :post round-tbl[:colnames yes](*this*)
build_matrix_expr <- function(expr) {
    if (is.name(expr)) {
        return(substitute(m(name), list(name = expr)))
    }

    if (is.call(expr)) {
        if (expr[[1]] == as.name("(")) return(build_matrix_expr(expr[[2]]))
        if (expr[[1]] == as.name("*") ||
            expr[[1]] == as.name("%*%")) {
            return(call("*",
                        build_matrix_expr(expr[[2]]),
                        build_matrix_expr(expr[[3]])))
        }
        if (expr[[1]] == as.name("+")) {
            return(call("+",
                        build_matrix_expr(expr[[2]]),
                        build_matrix_expr(expr[[3]])))
        }
    }

    stop(paste("Parse error for", expr))
}

# we need a quoted expression for this to work so R doesn't try to evaluate it before we manipulate it
build_matrix_expr(quote(A * B))

parse_matrix_expr <- function(expr) {
    expr <- substitute(expr)
    build_matrix_expr(expr)
}

parse_matrix_expr(A * B)

# get the quoted expression, build the matrix, and eval in parent frame
parse_matrix_expr <- function(expr) {
    expr <- substitute(expr)
    modified_expr <- build_matrix_expr(expr)
    eval(modified_expr, parent.frame())
}

parse_matrix_expr(A * B)
#+END_SRC

As an alternative, we can build the matrix expression directly using our constructor functions. 

#+BEGIN_SRC R :post round-tbl[:colnames yes](*this*)
build_matrix_expr <- function(expr, env) {
    if (is.call(expr)) {
        if (expr[[1]] == as.name("(")) return(build_matrix_expr(expr[[2]], env))
        if (expr[[1]] == as.name("*") ||
            expr[[1]] == as.name("%*%"))
            return(matrix_mult(build_matrix_expr(expr[[2]], env),
                               build_matrix_expr(expr[[3]], env)))
        if (expr[[1]] == as.name("+"))
            return(matrix_sum(build_matrix_expr(expr[[2]], env),
                              build_matrix_expr(expr[[3]], env)))
    }
    data_matrix <- m(eval(expr, env))
    attr(data_matrix, "def_expr") <- deparse(expr)
    data_matrix
}

parse_matrix_expr <- function(expr) {
    expr <- substitute(expr)
    build_matrix_expr(expr, parent.frame())
}

parse_matrix_expr(A * B + C + matrix(1, nrow = 10, ncol = 10))
#+END_SRC

** Expression Manipulation 

A template that doesn't do anything yet would look like this: 

#+BEGIN_SRC R :post round-tbl[:colnames yes](*this*)
rearrange_matrix_expr <- function(expr) {
    UseMethod("rearrange_matrix_expr")
}

rearrange_matrix_expr.matrix_data <- function(expr) {
    expr
}

rearrange_matrix_expr.matrix_mult <- function(expr) {
    matrix_mult(rearrange_matrix_expr(expr$left),
                rearrange_matrix_expr(expr$right))
}

rearrange_matrix_expr.matrix_sum <- function(expr) {
    matrix_sum(rearrange_matrix_expr(expr$left),
               rearrange_matrix_expr(expr$right))
}
#+END_SRC

** Optimizing Multiplication 

In the following implementation, we assume that we have a list of matrices as input. We collect their dimensions into a table, dims, for easy access. Then we create a table to represent the values and fill it using the previous equation. Once we have filled the table, we backtrack through it to work out the optimal way to multiply together the matrices from 1 to n, given the dimensions, table, and matrices 

#+BEGIN_SRC R :post round-tbl[:colnames yes](*this*)
arrange_optimal_matrix_mult <- function(matrices) {
    n <- length(matrices)
    dims <- matrix(0, nrow = n, ncol = 2)

    for (i in seq_along(matrices)) {
        dims[i, ] <- dim(matrices[[i]])
    }

    N <- matrix(0, nrow = n, ncol = n)

    for (len in 2:n) {
        for (i in 1:(n - len + 1)) {
            j <- i + len - 1
            k <- i:(j - 1)
            N[i, j] <- min(dims[i, 1] *
                           dims[k, 2] *
                           dims[j, 2] +
                           N[i, k] +
                           N[k + 1, j])
        }
    }
    # backtrack through the table 
    backtrack_matrix_mult(1, n, dims, N, matrices)
}

backtrack_matrix_mult <- function(i, j, dims, N, matrices) {
    if (i == j) {
        matrices[[i]]
    } else {
        k <- i:(j - 1)
        candidates <- dims[i, 1] * dims[k, 2] * dims[j, 2] + N[i, k] + N[k + 1, j]
        N[k + 1, j]
        split <- k[which(N[i, j] == candidates)][1]
        left <- backtrack_matrix_mult(i, split, dims, N, matrices)
        right <- backtrack_matrix_mult(split + 1, j, dims, N, matrices)
        matrix_mult(left, right)
    }
}
#+END_SRC

** Expression Rewriting 


